// Code generated by clickhousegen (https://github.com/mikluko/clickhousegen). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package {{ .PackageName }}

{{ if .Imports }}
import (
  {{- range .Imports }}
  "{{ . }}"
  {{- end }}
)
{{ end }}

{{- range .Struct.Fields }}
{{ if .Consts }}
    {{- $field := . }}
    const (
    {{- range $k, $v := .Consts }}
        {{ $field.Name }}{{ $k }} {{ $field.Type }} = "{{ $v }}"
    {{- end }}
    )
{{- end }}
{{- end }}

type {{ .Struct.Name }} struct {
  {{- range .Struct.Fields }}
  {{ .Name }} {{ .Type }} `{{ .Tag }}`
  {{- end }}
}
